#!/usr/bin/env python3
"""Inline the whole manuscript into one self-contained .tex, then prove it compiles.

Transport format for Overleaf, a reviewer, or anywhere the repository is not.
`paper/main.tex` stays the source of truth.

**This script must not be trusted to produce a working file unless --check passes.**
An earlier version inlined only the `\\input` directives in `main.tex` and silently left
the four nested ones inside the section files -- the pipeline figure and all three tables.
The result was shipped twice and died on Overleaf with an emergency stop. Recursion plus a
real compile is the whole point of this file; a bundler that is not compiled is a bundler
that is not known to work.

Usage:
    python scripts/bundle_paper.py            # write the bundle
    python scripts/bundle_paper.py --check    # write it, then compile it in a temp dir

Exit codes: 0 written (and compiled, with --check); 1 an \\input could not be resolved or
the compile failed.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "paper"
DEFAULT_OUT = ROOT / "dist" / "human-data-budget-paper-bundled.tex"
FIGURE = ROOT / "results/figures/pilot_nll_by_generation.png"

HEADER = """% =====================================================================
% BUNDLED SINGLE-FILE COPY -- generated by scripts/bundle_paper.py.
% DO NOT EDIT. Source of truth is paper/main.tex + paper/sections/*.tex.
%
% Every \\input is inlined recursively and the bibliography is embedded via
% filecontents, so this file needs no other .tex or .bib alongside it.
%
% ONE EXTERNAL ASSET. The results figure cannot be inlined. Upload
%   pilot_nll_by_generation.png
% next to this file (Overleaf: drag it into the project root).
% Without it the figure is missing; everything else still compiles.
%
% Compile: pdflatex -> bibtex -> pdflatex -> pdflatex
% (Overleaf does this automatically.)
%
% Result numbers are macros generated by scripts/generate_pilot_outputs.py
% from the chain artifacts of results/runs/primary_pilot_v2_2026-08-20.
% No number in this document was typed by hand.
% =====================================================================

"""

# Matches \input anywhere, not only alone on a line. The workshop file wraps one in
# {\small ...}; a line-anchored pattern skipped it and produced a bundle with no results
# table, which --check caught before it shipped. Group 1 is leading indentation, if any.
INPUT_RE = re.compile(r"([ \t]*)\\input\{([^}]*)\}")


def resolve(target: str) -> Path:
    for candidate in (PAPER / target, PAPER / (target + ".tex")):
        if candidate.is_file():
            return candidate
    raise SystemExit(f"bundle: cannot resolve \\input{{{target}}}")


def inline(text: str, seen: tuple[str, ...] = ()) -> str:
    """Replace every \\input with the file's contents, recursively."""

    def repl(m: re.Match) -> str:
        indent, target = m.group(1), m.group(2)
        if target in seen:
            raise SystemExit(f"bundle: \\input cycle through {target}")
        body = inline(resolve(target).read_text(encoding="utf-8").rstrip(),
                      seen + (target,))
        return (f"{indent}% ---------- begin {target} ----------\n"
                f"{body}\n"
                f"{indent}% ---------- end {target} ----------")

    return INPUT_RE.sub(repl, text)


def build(source: str) -> str:
    text = inline((PAPER / source).read_text(encoding="utf-8"))

    # The image lives outside paper/ in the repo. In a flat bundle it sits alongside.
    text = text.replace("{../results/figures/pilot_nll_by_generation}",
                        "{pilot_nll_by_generation}")

    bib = (PAPER / "references.bib").read_text(encoding="utf-8").rstrip()
    text = text.replace(
        "\\begin{document}",
        "\\begin{filecontents*}[overwrite]{references.bib}\n"
        + bib + "\n\\end{filecontents*}\n\n\\begin{document}", 1)

    if "\\input{" in text:
        leftover = re.findall(r"\\input\{[^}]*\}", text)
        raise SystemExit(f"bundle: unresolved \\input remains: {leftover}")
    return HEADER + text


def check(bundle: str) -> int:
    """Compile the bundle in a scratch directory containing nothing else."""
    exe = Path.home() / "AppData/Local/Programs/MiKTeX/miktex/bin/x64/pdflatex.exe"
    bibtex = exe.with_name("bibtex.exe")
    if not exe.is_file():
        print("check: no local pdflatex; skipping compile", file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp)
        (work / "main.tex").write_text(bundle, encoding="utf-8")
        if FIGURE.is_file():
            shutil.copy2(FIGURE, work / FIGURE.name)

        def run(cmd):
            return subprocess.run(cmd, cwd=work, capture_output=True, text=True)

        for step in ([str(exe), "-interaction=nonstopmode", "main.tex"],
                     [str(bibtex), "main"],
                     [str(exe), "-interaction=nonstopmode", "main.tex"],
                     [str(exe), "-interaction=nonstopmode", "main.tex"]):
            run(step)

        log = (work / "main.log")
        pdf = (work / "main.pdf")
        if not pdf.is_file():
            print("check: NO PDF PRODUCED", file=sys.stderr)
            if log.is_file():
                errs = [ln for ln in log.read_text(encoding="utf-8", errors="replace"
                                                   ).splitlines() if ln.startswith("! ")]
                print("\n".join(errs[:10]), file=sys.stderr)
            return 1

        text = log.read_text(encoding="utf-8", errors="replace")
        pages = re.search(r"Output written on main\.pdf \((\d+) pages", text)
        undef = len(re.findall(r"Warning.*(?:undefined|Citation)", text))
        over = len(re.findall(r"Overfull \\hbox", text))
        print(f"check: PDF produced, {pages.group(1) if pages else '?'} pages, "
              f"{undef} undefined, {over} overfull")
        return 0 if undef == 0 else 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="compile the bundle in a scratch dir and report")
    parser.add_argument("--main", default="main.tex",
                        help="which top-level .tex to bundle (main.tex or workshop_main.tex)")
    parser.add_argument("--out", type=Path, default=None,
                        help="output path; defaults next to the standard bundle")
    args = parser.parse_args()

    global OUT
    OUT = (ROOT / args.out if args.out else None) or (DEFAULT_OUT if args.main == "main.tex"
                       else DEFAULT_OUT.with_name("human-data-budget-workshop-bundled.tex"))
    bundle = build(args.main)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(bundle, encoding="utf-8")
    shown = OUT.relative_to(ROOT) if OUT.is_relative_to(ROOT) else OUT
    print(f"wrote {shown} ({OUT.stat().st_size / 1024:.0f} KB)")
    return check(bundle) if args.check else 0


if __name__ == "__main__":
    raise SystemExit(main())
