#!/usr/bin/env python3
"""Generate the manuscript's method and positive-control tables from committed sources.

No value here is typed by hand. The frozen policy constants come from
``configs/policy/joint.json`` and the positive-control metrics come from the
per-arm ``positive_control_result.json`` files the reproduction driver wrote.
This keeps CLAUDE.md rule 3 intact: numbers reach the manuscript only through
generated files.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BANNER = "% AUTO-GENERATED by scripts/generate_method_tables.py. DO NOT EDIT VALUES BY HAND."


def _threshold(key: str) -> str:
    """Render 'urgency_0_25_to_below_0_50' as a readable numeric condition."""
    nums = re.findall(r"(\d+)_(\d+)", key)
    vals = [f"{a}.{b}" for a, b in nums]
    if key.startswith("urgency_below"):
        return f"$u < {vals[0]}$"
    if key.startswith("urgency_at_least"):
        return f"$u \ge {vals[0]}$"
    return f"${vals[0]} \le u < {vals[1]}$"


def method_table(cfg: dict) -> str:
    rule = cfg["spending_rule"]
    ordered = sorted(rule.items(), key=lambda kv: rule[kv[0]])
    lines = [BANNER, "\\begin{tabular}{lr}", "Frozen parameter & Value \\\\", "\hline"]
    lines.append(f"Horizon & {cfg['horizon']} \\\\")
    lines.append(f"Lifetime human tokens & {cfg['lifetime_human_tokens']} \\\\")
    lines.append(f"Base generation spend & {cfg['base_generation_human_tokens']} \\\\")
    lines.append(f"Maximum generation spend & {cfg['maximum_generation_human_tokens']} \\\\")
    lines.append(f"Token granularity & {cfg['token_granularity']} \\\\")
    lines.append(f"Monitoring lag (generations) & {cfg['monitoring_lag_generations']} \\\\")
    lines.append("\hline")
    for key, spend in ordered:
        lines.append(f"Desired spend, {_threshold(key)} & {spend} \\\\")
    lines.append("\end{tabular}")
    return "\n".join(lines) + "\n"


def positive_control_table(arms: dict[str, dict]) -> str:
    gens = sorted({int(g) for a in arms.values() for g in a["metric_by_generation"]})
    lines = [BANNER, "\\begin{tabular}{rrr}",
             "Generation & Fully synthetic & Human mixed \\\\", "\hline"]
    for g in gens:
        cells = []
        for arm in ("fully_synthetic", "human_mixed"):
            v = arms[arm]["metric_by_generation"].get(str(g))
            cells.append(f"{v:.4f}" if v is not None else "--")
        lines.append(f"{g} & {cells[0]} & {cells[1]} \\\\")
    lines.append("\hline")
    ratios = [f"{arms[a]['degradation_ratio']:.4f}" for a in ("fully_synthetic", "human_mixed")]
    lines.append(f"Degradation ratio & {ratios[0]} & {ratios[1]} \\\\")
    lines.append("\end{tabular}")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--measurements", type=Path,
                    default=ROOT / "docs/positive_control/measurements_2026-08-17_rtx4090")
    ap.add_argument("--outdir", type=Path, default=ROOT / "paper/tables")
    args = ap.parse_args()

    cfg = json.loads((ROOT / "configs/policy/joint.json").read_text(encoding="utf-8"))
    (args.outdir / "method_hyperparameters.tex").write_text(method_table(cfg), encoding="utf-8")

    arms = {}
    for arm in ("fully_synthetic", "human_mixed"):
        path = args.measurements / arm / "positive_control_result.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        if data.get("fixture_only") or data.get("scientific_evidence") is False:
            raise SystemExit(f"refusing to typeset {path}: marked fixture output")
        arms[arm] = data
    (args.outdir / "positive_control.tex").write_text(
        positive_control_table(arms), encoding="utf-8")
    print("wrote method_hyperparameters.tex and positive_control.tex")


if __name__ == "__main__":
    main()
