#!/usr/bin/env python3
"""Generate final-format tables from fake schema-valid chain results.

Completes the tables half of the `docs/weekly/WEEK_2.md` Aarav deliverable
("Generate final-format tables and figures from fake schema-valid results");
`scripts/generate_figures.py` covers the figures half.

**These tables contain no experimental evidence.** They are produced by
``analysis.simulator``, which trains no model. The purpose is to freeze the
*format* — columns, ordering, rounding, caption — and to prove the
simulate → validate → aggregate → typeset pipeline runs end to end, so that when
real chain results exist the only change is the input path.

**Why this does not write to `paper/tables/`.** `paper/tables/primary_results.tex`
is the manuscript's result table and stays at `RESULT_PENDING` until real
artifacts exist (`PROTOCOL.md` §5). Writing fixture numbers there would put a
simulated value one `\\input` away from the abstract. Fixture output goes to
`results/tables/` instead, and the two are never the same file.

Every emitted chain result is validated against `schemas/chain_result.schema.json`
before aggregation, so "schema-valid" in the task description is enforced rather
than assumed.

Usage
-----
    python scripts/generate_fixture_tables.py --seeds 5
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tempfile
from pathlib import Path

from human_data_budget.analysis.generate import aggregate
from human_data_budget.analysis.metrics import (
    paired_bootstrap_interval,
    paired_mean_difference,
    regret_auc,
)
from human_data_budget.analysis.simulator import POLICY_NAMES, simulate_all_policies
from human_data_budget.runner.schema import validate_json

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "schemas" / "chain_result.schema.json"

FIXTURE_BANNER = (
    "% AUTO-GENERATED BY scripts/generate_fixture_tables.py -- DO NOT EDIT.\n"
    "% FIXTURE DATA. No language model was trained. Not scientific evidence.\n"
    "% This file must never be \\input by paper/ as a result table.\n"
)

POLICY_LABELS = {
    "random": "Fresh random rescue",
    "schedule_only": "Schedule-only",
    "selection_only": "Selection-only",
    "joint": "Joint (time $\\times$ mode)",
}


def write_chain_results(seeds: list[int], directory: Path) -> list[Path]:
    """Emit one schema-validated chain_result.json per policy per seed."""
    paths: list[Path] = []
    for seed in seeds:
        runs = simulate_all_policies(chain_seed=seed)
        for policy, run in runs.items():
            document = run["chain_result"]
            validate_json(document, SCHEMA)  # enforce "schema-valid", never assume it
            path = directory / f"{policy}_seed{seed}.json"
            path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
            paths.append(path)
    return paths


def primary_table(aggregated: dict[str, object]) -> str:
    """Chain-level primary outcome table, one row per treatment family."""
    lines = [
        FIXTURE_BANNER,
        "\\begin{tabular}{lrr}",
        "\\hline",
        "Policy & Chains & Mean NLL regret AUC \\\\",
        "\\hline",
    ]
    policies = aggregated.get("policies", {})
    for policy in POLICY_NAMES:
        values = policies.get(policy)
        if values is None:
            continue
        label = POLICY_LABELS.get(policy, policy.replace("_", "\\_"))
        lines.append(f"{label} & {values['chain_count']} & {values['mean_nll_auc']:.4f} \\\\")
    lines.extend(["\\hline", "\\end{tabular}", ""])
    return "\n".join(lines)


def contrast_table(runs_by_seed: dict[int, dict], seeds: list[int]) -> tuple[str, dict]:
    """Paired joint-minus-baseline contrasts with bootstrap intervals."""
    auc = {
        policy: {
            seed: regret_auc(
                [m["human_nll"] for m in runs_by_seed[seed][policy]["chain_result"]["metrics"]]
            )
            for seed in seeds
        }
        for policy in POLICY_NAMES
    }

    contrasts: dict[str, dict] = {}
    lines = [
        FIXTURE_BANNER,
        "\\begin{tabular}{lrr}",
        "\\hline",
        "Contrast (joint $-$ baseline) & Mean difference & 95\\% interval \\\\",
        "\\hline",
    ]
    for baseline in (policy for policy in POLICY_NAMES if policy != "joint"):
        difference = paired_mean_difference(auc["joint"], auc[baseline])
        low, high = paired_bootstrap_interval(auc["joint"], auc[baseline], seed=0)
        contrasts[baseline] = {"mean_difference": difference, "interval": [low, high]}
        label = POLICY_LABELS.get(baseline, baseline.replace("_", "\\_"))
        lines.append(f"{label} & {difference:.4f} & [{low:.4f}, {high:.4f}] \\\\")
    lines.extend(["\\hline", "\\end{tabular}", ""])
    return "\n".join(lines), contrasts


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--seeds", type=int, default=5)
    parser.add_argument("--table-dir", type=Path, default=ROOT / "results" / "tables")
    parser.add_argument(
        "--aggregate-out",
        type=Path,
        default=ROOT / "results" / "aggregates" / "fixture_primary.json",
    )
    args = parser.parse_args(argv)

    seeds = list(range(1, args.seeds + 1))
    runs_by_seed = {seed: simulate_all_policies(chain_seed=seed) for seed in seeds}

    with tempfile.TemporaryDirectory() as scratch:
        paths = write_chain_results(seeds, Path(scratch))
        aggregated = aggregate(paths)

    aggregated["fixture_only"] = True
    aggregated["scientific_evidence"] = False
    aggregated["chain_seeds"] = seeds

    args.aggregate_out.parent.mkdir(parents=True, exist_ok=True)
    args.aggregate_out.write_text(json.dumps(aggregated, indent=2) + "\n", encoding="utf-8")

    args.table_dir.mkdir(parents=True, exist_ok=True)
    primary_path = args.table_dir / "fixture_primary_results.tex"
    contrast_path = args.table_dir / "fixture_paired_contrasts.tex"

    primary_path.write_text(primary_table(aggregated), encoding="utf-8")
    contrast_text, contrasts = contrast_table(runs_by_seed, seeds)
    contrast_path.write_text(contrast_text, encoding="utf-8")

    digests = {
        path.name: hashlib.sha256(path.read_bytes()).hexdigest()
        for path in (primary_path, contrast_path, args.aggregate_out)
    }
    (args.table_dir / "table_provenance.json").write_text(
        json.dumps(
            {
                "schema_version": "1.0",
                "fixture_only": True,
                "scientific_evidence": False,
                "generator": "scripts/generate_fixture_tables.py",
                "chain_seeds": seeds,
                "sha256": digests,
                "paired_contrasts_joint_minus_baseline": contrasts,
                "warning": (
                    "Fixture tables. paper/tables/primary_results.tex is a separate file "
                    "and remains RESULT_PENDING until real artifacts exist."
                ),
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    for name, digest in digests.items():
        print(f"{digest}  {name}")
    print(f"validated {len(seeds) * len(POLICY_NAMES)} chain results against {SCHEMA.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
