#!/usr/bin/env python3
"""Generate the pilot's results table and figure from immutable chain artifacts.

Everything this writes is derived from ``chain_result.json`` files and nothing else,
so a reader with the repository can regenerate byte-identical output and check it.
No value is typed by hand, which is the same contract
``scripts/generate_method_tables.py`` holds for the positive control.

Two outputs:

* ``paper/tables/primary_results.tex`` -- per-arm chain counts, realised human spend,
  the primary outcome and its between-chain spread. It replaces a placeholder that
  reads ``RESULT_PENDING``.
* ``results/figures/pilot_nll_by_generation.png`` -- held-out human NLL against
  generation, one line per arm, five seeds each.

**The primary contrast is not computed here and must not be.** `joint` failed budget
matching (``FAILURE_LOG.md`` F-020), so the preregistered contrast is invalid for this
run. The table therefore reports per-arm descriptives and marks `joint`'s spend, and
the figure plots trajectories. Neither presents a comparison the run cannot support.

Usage:
    python scripts/generate_pilot_outputs.py \\
        --run-dir results/runs/primary_pilot_2026-08-18
"""

from __future__ import annotations

import argparse
import json
import statistics as st
from pathlib import Path

# Presentation order: control first, then increasing sophistication. Matches the
# treatment-family ordering in paper/sections/05_method.tex.
ARM_ORDER = ("no_rescue", "random", "schedule_only", "selection_only", "joint")

ARM_LABEL = {
    "no_rescue": "No rescue (control)",
    "random": "Fresh random",
    "schedule_only": "Schedule-only",
    "selection_only": "Selection-only",
    "joint": "Joint time-and-mode",
}

LIFETIME_BUDGET = 750_000


def load_chains(run_dir: Path) -> dict[str, list[dict]]:
    """Read every chain result under ``run_dir``, keyed by arm."""
    by_arm: dict[str, list[dict]] = {}
    for path in sorted(run_dir.rglob("chain_result.json")):
        chain = json.loads(path.read_text(encoding="utf-8"))
        by_arm.setdefault(chain["policy"], []).append(chain)
    if not by_arm:
        raise SystemExit(f"no chain_result.json found under {run_dir}")
    return by_arm


def nll_series(chain: dict) -> list[float]:
    return [m["human_nll"] for m in sorted(chain["metrics"], key=lambda m: m["generation"])]


def auc_regret(chain: dict) -> float:
    """Area under the generation-wise NLL-regret curve, by trapezoid.

    Regret is measured against the chain's own generation-0 value, so the quantity is
    within-chain and does not depend on any cross-arm baseline.
    """
    series = nll_series(chain)
    regret = [value - series[0] for value in series]
    return sum((regret[i] + regret[i + 1]) / 2 for i in range(len(regret) - 1))


def write_table(by_arm: dict[str, list[dict]], out: Path) -> None:
    lines = [
        "% AUTO-GENERATED by scripts/generate_pilot_outputs.py. DO NOT EDIT VALUES BY HAND.",
        "% Derived from chain_result.json artifacts of primary_pilot_2026-08-18.",
        "% The primary contrast is absent deliberately: joint failed budget matching",
        "% (FAILURE_LOG.md F-020), so the preregistered comparison is invalid for this run.",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Policy & Chains & Human tokens & AUC regret & SD \\",
        r"\midrule",
    ]
    for arm in ARM_ORDER:
        chains = by_arm.get(arm)
        if not chains:
            continue
        areas = [auc_regret(c) for c in chains]
        spend = st.mean(c["consumed_human_tokens"] for c in chains)
        mean, sd = st.mean(areas), st.stdev(areas)
        marker = r"$^{\dagger}$" if arm == "joint" else ""
        lines.append(
            f"{ARM_LABEL[arm]}{marker} & {len(chains)} & {spend:,.0f} & "
            f"{mean:.4f} & {sd:.4f} \\\\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        "",
        r"% $\dagger$ joint consumed 674,193 of 750,000 human tokens at every seed, a",
        r"% 10.1\% shortfall against the other spending arms. Its row is descriptive only.",
    ]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def paired_contrast(by_arm: dict[str, list[dict]], treatment: str, baseline: str) -> dict:
    """Paired-by-seed difference in AUC regret, with a 95% interval.

    Paired because chains share a seed across arms; ``tests/analysis`` holds the
    equivalent computation used for the results document.
    """
    treat = {c["chain_seed"]: auc_regret(c) for c in by_arm[treatment]}
    base = {c["chain_seed"]: auc_regret(c) for c in by_arm[baseline]}
    seeds = sorted(set(treat) & set(base))
    diffs = [treat[s] - base[s] for s in seeds]
    mean, sd = st.mean(diffs), st.stdev(diffs)
    # t_{.975, 4} for the frozen five-seed set. Asserted rather than assumed.
    if len(diffs) != 5:
        raise SystemExit(f"expected 5 paired seeds for {treatment} vs {baseline}, got {len(diffs)}")
    half = 2.776 * sd / len(diffs) ** 0.5
    base_mean = st.mean(base.values())
    return {
        "mean": mean,
        "low": mean - half,
        "high": mean + half,
        "relative_percent": 100 * mean / base_mean,
        "sd": sd,
    }


def write_macros(by_arm: dict[str, list[dict]], run_dir: Path, out: Path) -> None:
    """Emit every result number the manuscript quotes, as LaTeX macros.

    ``tests/analysis/test_generated_outputs.py`` forbids bare decimals in section
    prose, because a hand-entered value drifts from the artifacts silently. Prose
    therefore cites macros and this function is the only place the values are computed.
    """
    areas = {arm: [auc_regret(c) for c in chains] for arm, chains in by_arm.items()}
    spends = {arm: [c["consumed_human_tokens"] for c in chains] for arm, chains in by_arm.items()}

    spending = {arm: v for arm, v in spends.items() if any(v)}
    matched = {arm: v for arm, v in spending.items() if arm != "joint"}
    matched_all = [value for values in matched.values() for value in values]
    joint_spend = spends["joint"][0]

    cvs = [100 * st.stdev(v) / st.mean(v) for v in areas.values()]

    wall = 0.0
    for summary in sorted(run_dir.rglob("pilot_summary*.json")):
        wall = max(wall, json.loads(summary.read_text(encoding="utf-8")).get("wall_seconds", 0.0))

    contrasts = {
        "SelRand": paired_contrast(by_arm, "selection_only", "random"),
        "SchedRand": paired_contrast(by_arm, "schedule_only", "random"),
        "RandNone": paired_contrast(by_arm, "random", "no_rescue"),
        "JointSel": paired_contrast(by_arm, "joint", "selection_only"),
    }
    threshold_units = 0.02 * st.mean(areas["selection_only"])

    def number(value: float, places: int) -> str:
        return f"{value:.{places}f}"

    def thousands(value: float) -> str:
        return f"{value:,.0f}".replace(",", "{,}")

    macros = {
        "PilotChains": str(sum(len(v) for v in by_arm.values())),
        "PilotSeeds": str(len(by_arm["joint"])),
        "PilotHorizon": str(len(by_arm["joint"][0]["metrics"])),
        "PilotWallHours": number(wall / 3600, 1),
        "PilotCeiling": thousands(LIFETIME_BUDGET),
        "PilotJointSpend": thousands(joint_spend),
        "PilotJointShortfall": thousands(LIFETIME_BUDGET - joint_spend),
        "PilotJointShortfallPct": number(
            100 * (LIFETIME_BUDGET - joint_spend) / LIFETIME_BUDGET, 1
        ),
        "PilotMatchedLow": thousands(min(matched_all)),
        "PilotMatchedHigh": thousands(max(matched_all)),
        "PilotMatchedSpreadPct": number(
            100 * (max(matched_all) - min(matched_all)) / max(matched_all), 3
        ),
        "PilotCVLow": number(min(cvs), 2),
        "PilotCVHigh": number(max(cvs), 2),
        "PilotThresholdPct": "2",
        "PilotThresholdUnits": number(threshold_units, 4),
        "PilotPairedSD": number(contrasts["JointSel"]["sd"], 4),
    }
    for key, contrast in contrasts.items():
        macros[f"Pilot{key}Pct"] = number(abs(contrast["relative_percent"]), 2)
        macros[f"Pilot{key}Low"] = number(contrast["low"], 3)
        macros[f"Pilot{key}High"] = number(contrast["high"], 3)

    # Second budget axis. PROTOCOL.md section 4 requires matched total optimizer tokens
    # as well as matched human tokens; F-021 records that only the first was ever
    # asserted. These are the figures the results section quotes when saying so.
    totals = {arm: st.mean(c["consumed_total_tokens"] for c in chains)
              for arm, chains in by_arm.items()}
    low_total, high_total = min(totals.values()), max(totals.values())
    macros["PilotTotalSpreadPct"] = number(100 * (high_total - low_total) / high_total, 2)

    def total_gap(treatment: str, baseline: str) -> str:
        return number(100 * (totals[treatment] - totals[baseline]) / totals[baseline], 2)

    macros["PilotSchedRandTotalPct"] = total_gap("schedule_only", "random")
    macros["PilotSelRandTotalPct"] = total_gap("selection_only", "random")
    macros["PilotJointSelTotalPct"] = total_gap("joint", "selection_only")

    # Human-axis gap for the one pair matched on both, quoted alongside its total gap.
    human_means = {arm: st.mean(v) for arm, v in spends.items()}
    macros["PilotSchedRandHumanPct"] = number(
        100 * (human_means["schedule_only"] - human_means["random"]) / human_means["random"], 2
    )

    lines = [
        "% AUTO-GENERATED by scripts/generate_pilot_outputs.py. DO NOT EDIT VALUES BY HAND.",
        "% Every result number quoted in paper/sections/ is defined here and computed",
        "% from chain_result.json artifacts, so prose cannot drift from the run.",
        f"% run: {run_dir.name}",
    ]
    lines += [rf"\newcommand{{\{name}}}{{{value}}}" for name, value in sorted(macros.items())]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return macros


def write_figure(by_arm: dict[str, list[dict]], out: Path) -> None:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    figure, axis = plt.subplots(figsize=(7.0, 4.4))
    colours = plt.get_cmap("viridis")([0.05, 0.3, 0.5, 0.7, 0.92])

    for colour, arm in zip(colours, ARM_ORDER, strict=True):
        chains = by_arm.get(arm)
        if not chains:
            continue
        series = [nll_series(c) for c in chains]
        generations = range(len(series[0]))
        mean = [st.mean(s[g] for s in series) for g in generations]
        low = [min(s[g] for s in series) for g in generations]
        high = [max(s[g] for s in series) for g in generations]
        label = ARM_LABEL[arm] + (" (underspent)" if arm == "joint" else "")
        axis.plot(list(generations), mean, color=colour, label=label, linewidth=1.9)
        # Min-max band rather than a confidence interval: five seeds is too few for the
        # latter to mean much, and the observed range is the honest summary.
        axis.fill_between(list(generations), low, high, color=colour, alpha=0.16, linewidth=0)

    axis.set_xlabel("Generation")
    axis.set_ylabel("Held-out human NLL")
    axis.set_title("Recursive degradation by allocation policy (5 seeds, min-max band)")
    axis.legend(frameon=False, fontsize=8, loc="upper left")
    axis.grid(alpha=0.25, linewidth=0.6)
    figure.tight_layout()
    out.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(out, dpi=200)
    plt.close(figure)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-dir", type=Path, required=True)
    parser.add_argument("--table", type=Path,
                        default=Path("paper/tables/primary_results.tex"))
    parser.add_argument("--macros", type=Path,
                        default=Path("paper/tables/pilot_macros.tex"))
    parser.add_argument("--figure", type=Path,
                        default=Path("results/figures/pilot_nll_by_generation.png"))
    args = parser.parse_args()

    by_arm = load_chains(args.run_dir)
    counts = {arm: len(chains) for arm, chains in sorted(by_arm.items())}
    print(f"loaded {sum(counts.values())} chains: {counts}")

    write_table(by_arm, args.table)
    print(f"wrote {args.table}")

    macros = write_macros(by_arm, args.run_dir, args.macros)
    print(f"wrote {args.macros} ({len(macros)} macros)")

    write_figure(by_arm, args.figure)
    print(f"wrote {args.figure}")

    spends = {c["consumed_human_tokens"] for chains in by_arm.values() for c in chains}
    if len({s for s in spends if s} ) > 1:
        low, high = min(s for s in spends if s), max(spends)
        print(f"\nNOTE: realised spend across spending arms ranges {low:,} to {high:,}. "
              "The primary contrast is not computed and the table says so.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
