#!/usr/bin/env python3
"""Emit a pilot config for another model, identical to the GPT-2 one except where it cannot be.

Parity is the point. This copies ``configs/experiment/primary_pilot.json`` verbatim and
changes only four things: the model block, the manifest and corpus paths, the three budget
numbers, and the run identity. Everything the comparison depends on being equal -- arms,
seeds, horizon, training recipe, decoding, tail modes, effect threshold, exclusion rules --
is carried through untouched, so a diff of the two configs is a short and auditable list.

The budgets come from the rule in ``configs/experiment/cross_model_budget.json`` applied to
the model's own tokenisation of the corpus, never from a round number. Both inputs are
measured:

  T_model = T_gpt2 * (base_train optimizer tokens under this tokenizer / under GPT-2's)
  B       = round(f * T_model)

so a model whose tokenizer packs the corpus more tightly gets a proportionally smaller
budget and sits at the same operating point.

Prerequisite: build the model's manifests first, which is what produces the token counts.

    python scripts/add_optimizer_token_counts.py --tokenizer Qwen/Qwen2.5-0.5B \\
        --out-dir data/manifests/qwen
    python scripts/make_model_pilot.py --model qwen

Writes configs/experiment/pilot_<short_name>.json and prints the diff against GPT-2.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
BUDGET = REPO / "configs/experiment/cross_model_budget.json"
BASE = REPO / "configs/experiment/primary_pilot.json"
GPT2_COUNTS = REPO / "data/manifests/OPTIMIZER_TOKEN_COUNTS.json"


def die(message: str) -> None:
    print(f"CANNOT BUILD CONFIG: {message}", file=sys.stderr)
    raise SystemExit(2)


def read(path: Path, what: str) -> dict:
    if not path.exists():
        die(f"{what} not found at {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def base_train_tokens(counts: dict, where: Path) -> int:
    partitions = counts.get("partitions", {})
    entry = partitions.get("base_train")
    if not entry or "tokens" not in entry:
        die(f"{where} has no base_train token count; rerun add_optimizer_token_counts.py")
    return int(entry["tokens"])


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True, help="short_name from cross_model_budget.json")
    ap.add_argument("--manifest-dir", type=Path, default=None,
                    help="defaults to data/manifests/<short_name>")
    ap.add_argument("--out", type=Path, default=None)
    args = ap.parse_args()

    budget = read(BUDGET, "the frozen budget rule")
    base = read(BASE, "the GPT-2 pilot config")

    model = next((m for m in budget["models"] if m["short_name"] == args.model), None)
    if model is None:
        die(f"{args.model} is not in the budget config; known: "
            f"{[m['short_name'] for m in budget['models']]}")
    if args.model == "gpt2":
        die("gpt2 already has configs/experiment/primary_pilot.json; it satisfies the rule "
            "as executed and must not be regenerated")

    manifest_dir = args.manifest_dir or (REPO / "data/manifests" / args.model)
    counts_path = manifest_dir / "OPTIMIZER_TOKEN_COUNTS.json"
    counts = read(counts_path, f"token counts for {args.model}")
    if counts.get("tokenizer") != model["identifier"]:
        die(f"{counts_path} was built with {counts.get('tokenizer')}, not "
            f"{model['identifier']}")

    gpt2_counts = read(GPT2_COUNTS, "GPT-2 token counts")
    ratio = base_train_tokens(counts, counts_path) / base_train_tokens(gpt2_counts, GPT2_COUNTS)

    f = budget["rule"]["f"]
    t_gpt2 = budget["per_model_instantiation"]["gpt2_reference"]["total_optimizer_tokens"]
    total = round(t_gpt2 * ratio)
    lifetime = round(f * total)
    horizon = int(base["horizon"])

    config = json.loads(json.dumps(base))          # deep copy, key order preserved
    config["_comment_cross_model"] = (
        f"Generated by scripts/make_model_pilot.py from primary_pilot.json under the rule "
        f"in cross_model_budget.json. Tokenizer efficiency against GPT-2 on the same corpus: "
        f"{ratio:.6f}. Only the model block, manifest and corpus paths, budgets, and run "
        f"identity differ from the GPT-2 config."
    )
    config["run_id"] = f"cross_model_{args.model}"
    config["output_dir"] = f"runs/cross_model_{args.model}"
    config["artifact_destination"] = config["output_dir"]
    config["model"] = {
        "identifier": model["identifier"],
        "revision": model.get("revision", "PIN_BEFORE_RUNNING"),
        "tokenizer_revision": model.get("tokenizer_revision", "PIN_BEFORE_RUNNING"),
    }
    config["lifetime_human_budget"] = lifetime
    config["per_generation_human_budget"] = lifetime // horizon
    config["maximum_generation_human_budget"] = 2 * (lifetime // horizon)
    config["total_optimizer_tokens"] = total
    config["_budget_units"] = (
        f"Optimizer tokens under {model['identifier']}'s tokenizer. Derived, not chosen: "
        f"f={f} applied to T={total}, where T scales GPT-2's realised {t_gpt2} by this "
        f"model's tokenizer efficiency on the same 400 articles."
    )
    for name, entry in config.get("data", {}).get("manifests", {}).items():
        entry["path"] = f"data/manifests/{args.model}/{name}.jsonl"
    config["data"]["train_manifest"] = f"data/manifests/{args.model}/base_train.jsonl"
    config["data"].pop("train_manifest_sha256", None)
    config["data"].pop("_train_manifest_sha256_note", None)
    for key in list(config.get("data", {}).get("corpora", {})):
        config["data"]["corpora"][key] = (
            config["data"]["corpora"][key].replace("pilot_", f"{args.model}_")
        )

    out = args.out or (REPO / f"configs/experiment/pilot_{args.model}.json")
    out.write_text(json.dumps(config, indent=2) + "\n", encoding="utf-8")

    try:
        shown = out.resolve().relative_to(REPO)
    except ValueError:                      # --out may point outside the repo
        shown = out
    print(f"wrote {shown}")
    print(f"  model                    {model['identifier']}")
    print(f"  tokenizer efficiency     {ratio:.6f} x GPT-2 on the same corpus")
    print(f"  total optimizer tokens   {total:,}   (GPT-2: {t_gpt2:,})")
    print(f"  lifetime human budget    {lifetime:,}   (GPT-2 realised: 749,827)")
    print(f"  per generation           {lifetime // horizon:,}")
    print(f"  cap per generation       {2 * (lifetime // horizon):,}")
    print()
    print("  Pin the model revision before running; the config carries a placeholder.")
    print("  Everything else is byte-identical to the GPT-2 pilot config.")


if __name__ == "__main__":
    main()
