#!/usr/bin/env python3
"""Policy-behaviour report generated from fixture simulations.

Implements the `docs/weekly/WEEK_3.md` Aarav clause "Produce policy-behavior
report without changing frozen hyperparameters."

The report answers one question: **do the four treatment families actually
behave differently?** That question is separate from whether any of them is
better, and it must be answerable before outcomes are opened — a comparison
between policies that allocate identically is not a comparison at all.

**Fixture only. No language model is trained.** Numbers here describe the
simulator's chosen constants, not language. What the report legitimately
establishes is structural: which policies are distinguishable, whether budget
equality holds, and how allocation is distributed across generations and modes.

Usage
-----
    python scripts/policy_behavior_report.py --seeds 5
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

from human_data_budget.analysis.metrics import regret_auc
from human_data_budget.analysis.simulator import POLICY_NAMES, simulate_all_policies

ROOT = Path(__file__).resolve().parents[1]

HIDE_TAIL = frozenset({"tail"})


def _auc(run: dict) -> float:
    return regret_auc([metric["human_nll"] for metric in run["chain_result"]["metrics"]])


def _allocation_signature(run: dict) -> tuple:
    """Canonical form of a policy's allocation decisions across the chain."""
    return tuple(
        (step["generation"], tuple(sorted(step["mode_allocations"].items())))
        for step in run["allocations"]
    )


def build_report(seeds: list[int]) -> str:
    runs = {seed: simulate_all_policies(chain_seed=seed) for seed in seeds}
    blinded = {
        seed: {
            policy: simulate_all_policies(chain_seed=seed, hidden_modes=HIDE_TAIL)[policy]
            for policy in POLICY_NAMES
        }
        for seed in seeds
    }

    lines = [
        "# Policy Behaviour Report",
        "",
        "> **FIXTURE DATA — NOT SCIENTIFIC EVIDENCE.** Generated by",
        "> `scripts/policy_behavior_report.py` from `analysis.simulator`.",
        "> No language model was trained. Every number below is a property of the",
        "> simulator's chosen degradation and rescue constants.",
        "",
        f"Chain seeds: {seeds}. Horizon: "
        f"{runs[seeds[0]]['joint']['chain_result']['generations_completed']}.",
        "",
        "## 1. Budget equality",
        "",
        "`PROTOCOL.md` §4 requires identical lifetime human and total optimizer tokens",
        "across every policy in a comparison.",
        "",
        "| Policy | Lifetime human tokens | Total optimizer tokens |",
        "|---|---:|---:|",
    ]

    human_totals, total_totals = set(), set()
    for policy in POLICY_NAMES:
        result = runs[seeds[0]][policy]["chain_result"]
        human_totals.add(result["consumed_human_tokens"])
        total_totals.add(result["consumed_total_tokens"])
        lines.append(
            f"| `{policy}` | {result['consumed_human_tokens']} | "
            f"{result['consumed_total_tokens']} |"
        )

    matched = len(human_totals) == 1 and len(total_totals) == 1
    lines += [
        "",
        f"**Budget equality: {'HOLDS' if matched else 'VIOLATED'}.**",
        "",
        "Note that equality holding is a necessary condition, not evidence that the",
        "policies differ. Section 2 tests the latter.",
        "",
        "## 2. Are the policies distinguishable?",
        "",
        "Two policies are *indistinguishable* when their allocation decisions are",
        "identical at every generation on every seed. An indistinguishable pair cannot",
        "produce a meaningful contrast no matter how many chains are run.",
        "",
        "| Policy A | Policy B | Allocations identical | Regret AUC identical |",
        "|---|---|---|---|",
    ]

    degenerate_pairs = []
    for index, first in enumerate(POLICY_NAMES):
        for second in POLICY_NAMES[index + 1 :]:
            same_alloc = all(
                _allocation_signature(runs[seed][first])
                == _allocation_signature(runs[seed][second])
                for seed in seeds
            )
            same_auc = all(
                _auc(runs[seed][first]) == _auc(runs[seed][second]) for seed in seeds
            )
            if same_alloc:
                degenerate_pairs.append((first, second))
            lines.append(
                f"| `{first}` | `{second}` | {'YES' if same_alloc else 'no'} | "
                f"{'YES' if same_auc else 'no'} |"
            )

    lines += ["", f"**Degenerate pairs found: {len(degenerate_pairs)}.**"]
    if degenerate_pairs:
        for first, second in degenerate_pairs:
            lines.append(f"- `{first}` and `{second}` allocate identically on every seed.")
        lines += [
            "",
            "This is recorded as **F-001** in `FAILURE_LOG.md`. Until it is resolved,",
            "any contrast between a degenerate pair is structurally zero and the",
            "four-family decomposition required by C-002 is not yet testable.",
        ]

    lines += [
        "",
        "## 3. Allocation across generations and modes",
        "",
        f"Chain seed {seeds[0]}. Each cell is human tokens allocated to that mode.",
        "",
    ]

    generation_count = len(runs[seeds[0]]["joint"]["allocations"])
    header = " | ".join(f"g{index}" for index in range(generation_count))
    lines += [
        f"| Policy | {header} |",
        "|---" * (generation_count + 1) + "|",
    ]

    for policy in POLICY_NAMES:
        cells = []
        for step in runs[seeds[0]][policy]["allocations"]:
            allocations = step["mode_allocations"]
            cells.append(
                ", ".join(f"{mode}:{count}" for mode, count in sorted(allocations.items()))
                or "-"
            )
        lines.append(f"| `{policy}` | " + " | ".join(cells) + " |")

    lines += [
        "",
        "## 4. Monitoring-omission sensitivity",
        "",
        "Regret AUC with the full monitor versus with the `tail` mode hidden from the",
        "policy's view (the C-003 intervention). The mode still degrades in the true",
        "state; only the monitor is blinded.",
        "",
        "| Policy | Full monitor | Tail hidden | Change |",
        "|---|---:|---:|---:|",
    ]

    for policy in POLICY_NAMES:
        visible = sum(_auc(runs[seed][policy]) for seed in seeds) / len(seeds)
        hidden = sum(_auc(blinded[seed][policy]) for seed in seeds) / len(seeds)
        lines.append(
            f"| `{policy}` | {visible:.4f} | {hidden:.4f} | {hidden - visible:+.4f} |"
        )

    lines += [
        "",
        "A policy that ignores mode identity shows no change; a policy that targets",
        "modes is harmed. That separation is the intervention working as designed.",
        "",
        "## 5. What this report does not establish",
        "",
        "It does not show that any policy is better, that joint allocation helps, or",
        "that these effects hold for language models. It shows only which policies are",
        "structurally distinguishable and whether the accounting invariants hold.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--seeds", type=int, default=5)
    parser.add_argument(
        "--output", type=Path, default=ROOT / "results" / "policy_behavior_report.md"
    )
    args = parser.parse_args(argv)

    report = build_report(list(range(1, args.seeds + 1)))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")

    digest = hashlib.sha256(args.output.read_bytes()).hexdigest()
    print(f"{digest}  {args.output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
