#!/usr/bin/env bash
# Clean-environment installation and verification check.
#
# Implements the `docs/weekly/WEEK_4.md` Khantushig clauses "Test installation
# from a clean environment" and "Run lint, unit, contract, toy smoke, and
# documented reproduction commands".
#
# Builds a throwaway virtualenv, installs exactly what the documented quickstart
# installs, and runs every gate. Writes a machine-readable report so the result
# is an artifact rather than a claim in a chat log.
#
# This does NOT verify the positive control: that needs a GPU, torch, and
# transformers, none of which this repository declares. See COMPUTE.md.
#
# Usage:
#   bash scripts/verify_clean_install.sh [--keep-venv]
#
# Exit codes: 0 every gate passed, 1 at least one gate failed.

set -uo pipefail   # deliberately NOT -e: we want every gate to run and be recorded

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

VENV_DIR=".venv-clean"
REPORT="results/clean_install_report.md"
KEEP_VENV=0
[ "${1:-}" = "--keep-venv" ] && KEEP_VENV=1

mkdir -p results

declare -a NAMES=()
declare -a STATUSES=()
declare -a DETAILS=()

record() {
  NAMES+=("$1")
  STATUSES+=("$2")
  DETAILS+=("$3")
  printf '%-34s %s\n' "$1" "$2"
}

run_gate() {
  local name="$1"; shift
  local output
  if output=$("$@" 2>&1); then
    record "$name" "PASS" "$(printf '%s' "$output" | tail -n 1)"
  else
    record "$name" "FAIL" "$(printf '%s' "$output" | tail -n 3 | tr '\n' ' ')"
  fi
}

echo "Creating clean virtualenv at $VENV_DIR"
rm -rf "$VENV_DIR"
if ! python -m venv "$VENV_DIR"; then
  echo "FATAL: could not create virtualenv" >&2
  exit 1
fi

if [ -x "$VENV_DIR/bin/python" ]; then
  PY="$VENV_DIR/bin/python"          # POSIX
else
  PY="$VENV_DIR/Scripts/python.exe"  # Windows
fi

# Gate 1: pip must be new enough for a PEP 660 editable install of this
# pyproject. pip < 23.1 fails with "File setup.py or setup.cfg not found",
# which is a genuine and easily-missed environment defect.
PIP_VERSION="$("$PY" -m pip --version 2>/dev/null | awk '{print $2}')"
PIP_MAJOR="${PIP_VERSION%%.*}"
if [ "${PIP_MAJOR:-0}" -ge 23 ]; then
  record "pip supports PEP 660 editable" "PASS" "pip $PIP_VERSION"
else
  record "pip supports PEP 660 editable" "FAIL" \
    "pip $PIP_VERSION is older than 23.1; 'pip install -e .' will fail on this pyproject"
fi

run_gate "locked, hash-checked install" \
  "$PY" -m pip install --require-hashes -r requirements-lock.txt
run_gate "editable package install" \
  "$PY" -m pip install -e . --no-deps
run_gate "dev extra install" \
  "$PY" -m pip install -e ".[dev]"
run_gate "lint" "$PY" -m ruff check .
run_gate "unit and contract tests" "$PY" -m pytest -q
run_gate "repository audit" \
  "$PY" scripts/audit_repository.py --strict-structure
run_gate "toy smoke chain" \
  "$PY" -m human_data_budget.runner.chain --config configs/experiment/toy_cpu.json
run_gate "preflight budget check" \
  "$PY" scripts/preflight_budget.py configs/experiment/toy_cpu.json

FAILURES=0
for status in "${STATUSES[@]}"; do
  [ "$status" = "FAIL" ] && FAILURES=$((FAILURES + 1))
done

{
  echo "# Clean Install Verification Report"
  echo
  echo "Generated by \`scripts/verify_clean_install.sh\`."
  echo
  echo "- Repository: \`$REPO_ROOT\`"
  echo "- Interpreter: \`$("$PY" --version 2>&1)\`"
  echo "- pip: \`$PIP_VERSION\`"
  echo "- Gates run: ${#NAMES[@]}"
  echo "- Failures: $FAILURES"
  echo
  echo "| Gate | Result | Detail |"
  echo "|---|---|---|"
  for index in "${!NAMES[@]}"; do
    detail="$(printf '%s' "${DETAILS[$index]}" | sed 's/|/\\|/g' | cut -c1-160)"
    echo "| ${NAMES[$index]} | ${STATUSES[$index]} | $detail |"
  done
  echo
  echo "## Scope"
  echo
  echo "This report covers installation and the CPU gates only. It does **not**"
  echo "verify the Stage A positive control, which requires a GPU plus torch and"
  echo "transformers — neither is declared by this repository. See COMPUTE.md and"
  echo "\`docs/evidence/upstream_pin.md\` §5."
} > "$REPORT"

echo
echo "Report written to $REPORT ($FAILURES failure(s))"

if [ "$KEEP_VENV" -eq 0 ]; then
  rm -rf "$VENV_DIR"
fi

[ "$FAILURES" -eq 0 ]
